name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5

      - name: Toolchain
        run: |
          rustc --version
          cargo --version

      - name: Test
        run: cargo test --locked

      - name: Format
        continue-on-error: true
        run: cargo fmt --check
